name: GitHub Super-Linter

on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Lint Code Base
        uses: github/super-linter@v4.8.3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
